package main

type Monkeys = []string

var monkeys = Monkeys{
	"Agile Mangabey",
	"Allen’S Swamp Monkey",
	"Alta Floresta Titi",
	"Amazon Black Howler",
	"Andean Night Monkey",
	"Andean Saddle-Back Tamarin",
	"Angolan Colobus",
	"Angolan Talapoin",
	"Annamese Silvered Langur",
	"Aracá Uakari",
	"Arunachal Macaque",
	"Ashy Black Titi",
	"Ashy Red Colobus",
	"Assam Macaque",
	"Atlantic Titi",
	"Azara’S Night Monkey",
	"Bald Uakari",
	"Bale Monkey",
	"Banded Langur",
	"Barbara Brown’S Titi",
	"Barbary Macaque",
	"Bare-Eared Squirrel Monkey",
	"Bearded Capuchin",
	"Bearded Saki",
	"Bengal Sacred Langur",
	"Black And White Langur",
	"Black Bearded Saki",
	"Black Capuchin",
	"Black Colobus",
	"Black Howler Monkey",
	"Black Lion Tamarin",
	"Black Snub-Nosed Monkey",
	"Black Spider Monkey",
	"Black Squirrel Monkey",
	"Black Sumatran Langur",
	"Black Tamarin",
	"Black Titi",
	"Black Uakari",
	"Black-Capped Squirrel Monkey",
	"Black-Crested Mangabey",
	"Black-Crested Sumatran Langur",
	"Black-Faced Lion Tamarin",
	"Black-Footed Gray Langur",
	"Black-Fronted Titi",
	"Black-Headed Marmoset",
	"Black-Headed Night Monkey",
	"Black-Headed Spider Monkey",
	"Black-Mantled Tamarin",
	"Black-Shanked Douc Langur",
	"Black-Tailed Marmoset",
	"Black-Tufted Marmoset",
	"Blond Capuchin",
	"Blue Monkey",
	"Blue Nile Patas Monkey",
	"Bolivian Red Howler",
	"Bonnet Macaque",
	"Booted Macaque",
	"Bouvier’S Red Colobus",
	"Brazilian Bare-Faced Tamarin",
	"Brown Howler Monkey",
	"Brown Titi",
	"Brown Weeper Capuchin",
	"Brown-Backed Bearded Saki",
	"Brown-Mantled Tamarin",
	"Brumback’S Night Monkey",
	"Buffy-Headed Marmoset",
	"Buffy-Tufted Marmoset",
	"Burnished Saki",
	"Campbell’S Mona Monkey",
	"Capped Langur",
	"Caquetá Titi",
	"Cat Ba Langur",
	"Cazuza’S Saki",
	"Central American Squirrel Monkey",
	"Chacma Baboon",
	"Chacoan Titi Monkey",
	"Chestnut-Bellied Titi",
	"Coastal Black-Handed Titi",
	"Coimbra Filho’S Titi",
	"Collared Mangabey",
	"Collared Titi",
	"Collins’ Squirrel Monkey",
	"Colombian Black-Handed Titi",
	"Common Marmoset",
	"Coppery Titi",
	"Cotton-Top Tamarin",
	"Crab-Eating Macaque",
	"Crested Black Macaque",
	"Crested Mona Monkey",
	"Cross Marked Langur",
	"Cruz Lima’S Saddleback Tamarin",
	"De Brazza’S Monkey",
	"Delacour’S Langur",
	"Dent’S Mona Monkey",
	"Diana Monkey",
	"Drill",
	"Dryas Monkey",
	"Dusky Langur",
	"East Javan Langur",
	"East Sumatran Banded Langur",
	"Eastern Black-Handed Tamarin",
	"Eastern Pygmy Marmoset",
	"Ecuadorian Capuchin",
	"Ecuadorian Squirrel Monkey",
	"Emilia’S Marmoset",
	"Emperor Tamarin",
	"Equatorial Saki",
	"Foa’S Red Colobus",
	"Formosan Rock Macaque",
	"François’ Langur",
	"Gabon Talapoin",
	"Gee’S Golden Langur",
	"Gelada",
	"Geoffroy’S Monk Saki",
	"Geoffroy’S Saddleback Tamarin",
	"Geoffroy’S Spider Monkey",
	"Geoffroy’S Tamarin",
	"Germain’S Langur",
	"Goeldi’S Monkey",
	"Gold-And-White Marmoset",
	"Golden Angwantibo",
	"Orange Monkeys",
	"Golden Lion Tamarin",
	"Golden Snub-Nosed Monkey",
	"Golden-Bellied Capuchin",
	"Golden-Bellied Mangabey",
	"Golden-Faced Saki",
	"Golden-Headed Lion Tamarin",
	"Golden-Mantled Tamarin",
	"Gorontalo Macaques",
	"Gorontalo Macaque",
	"Gray Snub-Nosed Monkey",
	"Gray-Cheeked Mangabey",
	"Gray-Shanked Douc Langur",
	"Gray’S Bald-Faced Saki",
	"Greater Spot-Nosed Monkey",
	"Green Monkey",
	"Grivet Monkey",
	"Guianan Brown Capuchin",
	"Guianan Saki",
	"Guianan Squirrel Monkey",
	"Guianan Weeper Capuchin",
	"Guinea Baboon",
	"Guyanan Red Howler Monkey",
	"Hairy Saki",
	"Hamadryas Baboon",
	"Hamlyn’S Monkey",
	"Hatinh Langur",
	"Heck’S Macaque",
	"Hershkovitz’S Marmoset",
	"Highland Mangabey",
	"Hoffmann’S Titi",
	"Hooded Capuchin",
	"Hose’S Langur",
	"Humboldt’S Night Monkey",
	"Humboldt’S Squirrel Monkey",
	"Humboldt’S White Capuchin",
	"Humboldt’S Woolly Monkey",
	"Illiger’S Saddle-Back Tamarin",
	"Indochinese Black Langur",
	"Indochinese Grey Langur",
	"Isabel’S Saki",
	"Japanese Macaque",
	"Javan Surili",
	"Kaapori Capuchin",
	"Kashmir Gray Langur",
	"Kinda Baboon",
	"King Colobus",
	"Lake Baptista Titi",
	"Lang’S Red Colobus",
	"Laotian Langur",
	"Lesser Spotted-Nosed Monkey",
	"Lesson’S Saddle-Back Tamarin",
	"Lesula",
	"Lion-Tailed Macaque",
	"Lomami Red Colobus",
	"Lowe’S Mona Monkey",
	"Lucifer Titi",
	"Madidi Titi",
	"Malbrouck",
	"Mandrill",
	"Mantled Guereza",
	"Mantled Howler Monkey",
	"Maranhão Red-Handed Howler",
	"Marca’S Marmoset",
	"Maroon Langur",
	"Martins’ Tamarin",
	"Maués Marmoset",
	"Mentawai Langur",
	"Midas Tamarin",
	"Miller’S Langur",
	"Miller’S Saki",
	"Milton’S Titi",
	"Miss Waldron’S Red Colobus",
	"Mitered Langur",
	"Mittermeier’S Tapajós Saki",
	"Mona Monkey",
	"Moor Macaque",
	"Mottle-Faced Tamarin",
	"Mount Kilimanjaro Guereza",
	"Moustached Guenon",
	"Moustached Tamarin",
	"Munduruku Marmoset",
	"Myanmar Snub-Nosed Monkey",
	"Nancy Ma’S Night Monkey",
	"Napo Saki",
	"Natuna Island Surili",
	"Neblina Uakari",
	"Gray Monkeys",
	"Nepal Gray Langur",
	"Niger Delta Red Colobus",
	"Nilgiri Langur",
	"North Sumatran Leaf Monkey",
	"Northern Muriqui",
	"Northern Pig-Tailed Macaque",
	"Olive Baboon",
	"Olive Colobus",
	"Ollala Brothers’ Titi",
	"Ornate Titi",
	"Oustalet’S Red Colobus",
	"Pagai Island Macaque",
	"Pale-Thighed Langur",
	"Panamanian Night Monkey",
	"Panamanian White-Faced Capuchin",
	"Parecis Titi",
	"Patas Monkey",
	"Pennant’S Red Colobus",
	"Peruvian Spider Monkey",
	"Peruvian White-Fronted Capuchin",
	"Peruvian Yellow-Tailed Woolly Monkey",
	"Phayre’S Langur",
	"Pig-Tailed Langur",
	"Pissinatti’S Bald-Faced Saki",
	"Popa Langur",
	"Preuss’S Monkey",
	"Preuss’S Red Colobus",
	"Prince Bernhard’S Titi",
	"Proboscis Monkey",
	"Purple-Faced Langur",
	"Pygmy Marmoset",
	"Red Howler Monkey",
	"Red-Backed Bearded Saki",
	"Red-Bellied Monkey",
	"Red-Bellied Titi",
	"Red-Chested Mustached Tamarin",
	"Red-Eared Guenon",
	"Red-Handed Howler",
	"Red-Headed Titi",
	"Red-Mantled Saddle-Back Tamarin",
	"Red-Shanked Douc Langur",
	"Rhesus Macaque",
	"Rio Acari Marmoset",
	"Rio Beni Titi",
	"Río Cesar White-Fronted Capuchin",
	"Rio Mayo Titi",
	"Robinson’S Banded Langur",
	"Robust Capuchin Monkey",
	"Roloway Monkey",
	"Rondon’S Marmoset",
	"Roosmalens’ Dwarf Marmoset",
	"Ryland’S Bald-Faced Saki",
	"Saban Grizzled Langur",
	"Sanje Mangabey",
	"Santa Marta White-Fronted Capuchin",
	"Santarem Marmoset",
	"Satéré Marmoset",
	"Schmidt’S Red-Tailed Monkey",
	"Sclater’S Guenon",
	"Selangor Silvered Langur",
	"Semliki Red Colobus",
	"Shan State Langur",
	"Shock-Headed Capuchin",
	"Shortridge’S Capped Langur",
	"Siberut Langur",
	"Siberut Macaque",
	"Sierra De Perijá White-Fronted Capuchin",
	"Silvered Langur",
	"Silvery Brown Bare-Face Tamarin",
	"Silvery Marmoset",
	"Sooty Mangabey",
	"Southern Muriqui",
	"Spix’S Night Monkey",
	"Spix’S Red-Handed Howler",
	"Spix’S White-Fronted Capuchin",
	"Stephen Nash’S Titi",
	"Stump-Tailed Macaque",
	"Sun-Tailed Monkey",
	"Sunda Pig-Tailed Macaque",
	"Tana River Mangabey",
	"Tana River Red Colobus",
	"Tantalus Monkey",
	"Tarai Gray Langur",
	"Tenasserim Langur",
	"Thollon’S Red Colobus",
	"Tibetan Macaque",
	"Tonkean Macaque",
	"Tonkin Snub-Nosed Monkey",
	"Toppin’S Titi",
	"Toque Macaque",
	"Tufted Gray Langur",
	"Udzungwa Red Colobus",
	"Ulindi River Red Colobus",
	"Ursine Colobus",
	"Ursine Howler",
	"Urubamba Brown Titi",
	"Uta Hick’S Bearded Saki",
	"Vanzolini’S Bald-Faced Saki",
	"Varied White-Fronted Capuchin",
	"Variegated Spider Monkey",
	"Vervet Monkey",
	"Vieira’S Titi",
	"Weddell’S Saddle-Back Tamarin",
	"Weeping Capuchin",
	"West Javan Langur",
	"Western Red Colobus",
	"White Marmoset",
	"White-Bellied Spider Monkey",
	"White-Cheeked Macaque",
	"White-Cheeked Spider Monkey",
	"White-Eared Titi",
	"White-Footed Saki",
	"White-Fronted Langur",
	"White-Headed Langur",
	"White-Headed Marmoset",
	"White-Naped Mangabey",
	"White-Nosed Saki",
	"White-Tailed Titi",
	"White-Throated Capuchin",
	"Wied’S Marmoset",
	"Wolf’S Mona Monkey",
	"Yellow Baboon",
	"Yucatan Black Howler",
	"Zanzibar Red Colobus",
}
