package english

type Snake = string

var snakes = []Snake{
	"Viper Adder",
	"Common Adder",
	"Death Adder",
	"Desert Death Adder",
	"Horned Adder",
	"Long-Nosed Adder",
	"Many-Horned Adder",
	"Mountain Adder",
	"Mud Adder",
	"Namaqua Dwarf Adder",
	"Peringuey'S Adder",
	"Puff Adder",
	"African Puff Adder",
	"Rhombic Night Adder",
	"Sand Adder",
	"Dwarf Sand Adder",
	"Namib Dwarf Sand Adder",
	"Water Adder",
	"Aesculapian Snake",
	"Anaconda",
	"Bolivian Anaconda",
	"De Schauensee'S Anaconda",
	"Green Anaconda",
	"Yellow Anaconda",
	"Arafura File Snake",
	"Asp",
	"European Asp",
	"Egyptian Asp",
	"African Beaked Snake",
	"Ball Python",
	"Bird Snake",
	"Black-Headed Snake",
	"Mexican Black Kingsnake",
	"Black Rat Snake",
	"Black Snake",
	"Red-Bellied Black Snake",
	"Blind Snake",
	"Brahminy Blind Snake",
	"Texas Blind Snake",
	"Western Blind Snake",
	"Boa",
	"Abaco Island Boa",
	"Amazon Tree Boa",
	"Boa Constrictor",
	"Cuban Boa",
	"Dumeril'S Boa",
	"Dwarf Boa",
	"Emerald Tree Boa",
	"Hogg Island Boa",
	"Jamaican Boa",
	"Madagascar Ground Boa",
	"Madagascar Tree Boa",
	"Puerto Rican Boa",
	"Rainbow Boa",
	"Red-Tailed Boa",
	"Rosy Boa",
	"Rubber Boa",
	"Sand Boa",
	"Tree Boa",
	"Boiga",
	"Boomslang",
	"Brown Snake",
	"Eastern Brown Snake",
	"Bull Snake",
	"Bushmaster",
	"Dwarf Beaked Snake",
	"Rufous Beaked Snake",
	"Canebrake",
	"Cantil",
	"Cascabel",
	"Cat-Eyed Snake",
	"Banded Cat-Eyed Snake",
	"Green Cat-Eyed Snake",
	"Cat Snake",
	"Andaman Cat Snake",
	"Beddome'S Cat Snake",
	"Dog-Toothed Cat Snake",
	"Forsten'S Cat Snake",
	"Gold-Ringed Cat Snake",
	"Gray Cat Snake",
	"Many-Spotted Cat Snake",
	"Nicobar Cat Snake",
	"Sri Lanka Cat Snake",
	"Tawny Cat Snake",
	"Chicken Snake",
	"Coachwhip Snake",
	"Cobra",
	"Andaman Cobra",
	"Arabian Cobra",
	"Asian Cobra",
	"Banded Water Cobra",
	"Black-Necked Cobra",
	"Black-Necked Spitting Cobra",
	"Black Tree Cobra",
	"Burrowing Cobra",
	"Cape Cobra",
	"Caspian Cobra",
	"Chinese Cobra",
	"Cobra De Capello",
	"Congo Water Cobra",
	"Common Cobra",
	"Eastern Water Cobra",
	"Egyptian Cobra",
	"Equatorial Spitting Cobra",
	"False Cobra",
	"False Water Cobra",
	"Forest Cobra",
	"Gold Tree Cobra",
	"Indian Cobra",
	"Indochinese Spitting Cobra",
	"Javan Spitting Cobra",
	"King Cobra",
	"Mandalay Cobra",
	"Monocled Cobra",
	"Monoculate Cobra",
	"Mozambique Spitting Cobra",
	"North Philippine Cobra",
	"Nubian Spitting Cobra",
	"Philippine Cobra",
	"Red Spitting Cobra",
	"Rinkhals Cobra",
	"Shield-Nosed Cobra",
	"Sinai Desert Cobra",
	"Southern Indonesian Spitting Cobra",
	"Southern Philippine Cobra",
	"Southwestern Black Spitting Cobra",
	"Snouted Cobra",
	"Spectacled Cobra",
	"Spitting Cobra",
	"Storm Water Cobra",
	"Thai Cobra",
	"Taiwan Cobra",
	"West African Brown Spitting Cobra",
	"White-Lipped Cobra",
	"Yellow Cobra",
	"Zebra Spitting Cobra",
	"Collett'S Snake",
	"Congo Snake",
	"Copperhead",
	"American Copperhead",
	"Australian Copperhead",
	"Coral Snake",
	"Arizona Coral Snake",
	"Beddome'S Coral Snake",
	"Brazilian Coral Snake",
	"Cape Coral Snake",
	"Eastern Coral Snake",
	"False Coral Snake",
	"Harlequin Coral Snake",
	"High Woods Coral Snake",
	"Malayan Long-Glanded Coral Snake",
	"Texas Coral Snake",
	"Western Coral Snake",
	"Corn Snake",
	"South Eastern Corn Snake",
	"Cottonmouth",
	"Crowned Snake",
	"Cuban Wood Snake",
	"Eastern Hognose Snake",
	"Egg-Eater",
	"Indian Egg-Eater",
	"Eyelash Viper",
	"Eastern Coral Snake",
	"Fer-De-Lance",
	"Fierce Snake",
	"Fishing Snake",
	"Flying Snake",
	"Golden Tree Snake",
	"Indian Flying Snake",
	"Moluccan Flying Snake",
	"Ornate Flying Snake",
	"Paradise Flying Snake",
	"Twin-Barred Tree Snake",
	"Banded Flying Snake",
	"Forest Flame Snake",
	"Garter Snake",
	"Checkered Garter Snake",
	"Common Garter Snake",
	"San Francisco Garter Snake",
	"Texas Garter Snake",
	"Glossy Snake",
	"Gopher Snake",
	"Cape Gopher Snake",
	"Grass Snake",
	"Green Snake",
	"Rough Green Snake",
	"Smooth Green Snake",
	"Ground Snake",
	"Common Ground Snake",
	"Three-Lined Ground Snake",
	"Western Ground Snake",
	"Habu",
	"Himehabu",
	"Okinawan Habu",
	"Sakishima Habu",
	"Tokara Habu",
	"Harlequin Snake",
	"Elaps Harlequin Snake",
	"Herald Snake",
	"Hognose Snake",
	"Blonde Hognose Snake",
	"Dusty Hognose Snake",
	"Eastern Hognose Snake",
	"Jan'S Hognose Snake",
	"Giant Malagasy Hognose Snake",
	"Mexican Hognose Snake",
	"Plains Hognose Snake",
	"Ringed Hognose Snake",
	"South American Hognose Snake",
	"Southern Hognose Snake",
	"Speckled Hognose Snake",
	"Tri-Color Hognose Snake",
	"Western Hognose Snake",
	"Hoop Snake",
	"Hundred Pacer",
	"Ikaheka Snake",
	"Indigo Snake",
	"Jamaican Tree Snake",
	"Jararacussu",
	"Keelback",
	"Andrea'S Keelback",
	"Asian Keelback",
	"Assam Keelback",
	"Black-Striped Keelback",
	"Buff Striped Keelback",
	"Burmese Keelback",
	"Checkered Keelback",
	"Common Keelback",
	"Hill Keelback",
	"Himalayan Keelback",
	"Khasi Hills Keelback",
	"Modest Keelback",
	"Nicobar Island Keelback",
	"Nilgiri Keelback",
	"Orange-Collared Keelback",
	"Red-Necked Keelback",
	"Sikkim Keelback",
	"Speckle-Bellied Keelback",
	"Tiger Keelback",
	"Wall'S Keelback",
	"White-Lipped Keelback",
	"Wynaad Keelback",
	"Yunnan Keelback",
	"King Brown",
	"King Cobra",
	"King Snake",
	"California Kingsnake",
	"Desert Kingsnake",
	"Grey-Banded Kingsnake",
	"North Eastern King Snake",
	"Prairie Kingsnake",
	"Scarlet Kingsnake",
	"Speckled Kingsnake",
	"Krait",
	"Banded Krait",
	"Blue Krait",
	"Black Krait",
	"Burmese Krait",
	"Ceylon Krait",
	"Indian Krait",
	"Lesser Black Krait",
	"Malayan Krait",
	"Many-Banded Krait",
	"Northeastern Hill Krait",
	"Red-Headed Krait",
	"Sind Krait",
	"South Andaman Krait",
	"Suzhen'S Krait",
	"Large Shield Snake",
	"Lancehead",
	"Common Lancehead",
	"Lora",
	"Grey Lora",
	"Lyre Snake",
	"Baja California Lyresnake",
	"Central American Lyre Snake",
	"Texas Lyre Snake",
	"Eastern Lyre Snake",
	"Machete Savane",
	"Mamba",
	"Black Mamba",
	"Green Mamba",
	"Eastern Green Mamba",
	"Western Green Mamba",
	"Mamushi",
	"Mangrove Snake",
	"Milk Snake",
	"Moccasin Snake",
	"Montpellier Snake",
	"Mud Snake",
	"Eastern Mud Snake",
	"Western Mud Snake",
	"Mussurana",
	"Night Snake",
	"Cat-Eyed Night Snake",
	"Texas Night Snake",
	"Nichell Snake",
	"Narrowhead Garter Snake",
	"Nose-Horned Viper",
	"Rhinoceros Viper",
	"Vipera Ammodytes",
	"Parrot Snake",
	"Mexican Parrot Snake",
	"Patchnose Snake",
	"Perrotet'S Shieldtail Snake",
	"Pine Snake",
	"Pipe Snake",
	"Asian Pipe Snake",
	"Dwarf Pipe Snake",
	"Red-Tailed Pipe Snake",
	"Python",
	"African Rock Python",
	"Amethystine Python",
	"Angolan Python",
	"Australian Scrub Python",
	"Ball Python",
	"Bismarck Ringed Python",
	"Black Headed Python",
	"Blood Python",
	"Boelen Python",
	"Borneo Short-Tailed Python",
	"Bredl'S Python",
	"Brown Water Python",
	"Burmese Python",
	"Calabar Python",
	"Western Carpet Python",
	"Centralian Carpet Python",
	"Coastal Carpet Python",
	"Inland Carpet Python",
	"Jungle Carpet Python",
	"New Guinea Carpet Python",
	"Northwestern Carpet Python",
	"Southwestern Carpet Python",
	"Children'S Python",
	"Dauan Island Water Python",
	"Desert Woma Python",
	"Diamond Python",
	"Flinders Python",
	"Green Tree Python",
	"Halmahera Python",
	"Indian Python",
	"Indonesian Water Python",
	"Macklot'S Python",
	"Moluccan Python",
	"Oenpelli Python",
	"Olive Python",
	"Papuan Python",
	"Pygmy Python",
	"Red Blood Python",
	"Reticulated Python",
	"Kayaudi Dwarf Reticulated Python",
	"Selayer Reticulated Python",
	"Rough-Scaled Python",
	"Royal Python",
	"Savu Python",
	"Spotted Python",
	"Stimson'S Python",
	"Sumatran Short-Tailed Python",
	"Tanimbar Python",
	"Timor Python",
	"Wetar Island Python",
	"White-Lipped Python",
	"Brown White-Lipped Python",
	"Northern White-Lipped Python",
	"Southern White-Lipped Python",
	"Woma Python",
	"Western Woma Python",
	"Queen Snake",
	"Racer",
	"Bimini Racer",
	"Buttermilk Racer",
	"Eastern Racer",
	"Eastern Yellowbelly Sad Racer",
	"Mexican Racer",
	"Southern Black Racer",
	"Tan Racer",
	"West Indian Racer",
	"Raddysnake",
	"Southwestern Blackhead Snake",
	"Rat Snake",
	"Baird'S Rat Snake",
	"Beauty Rat Snake",
	"Great Plains Rat Snake",
	"Green Rat Snake",
	"Japanese Forest Rat Snake",
	"Japanese Rat Snake",
	"King Rat Snake",
	"Mandarin Rat Snake",
	"Persian Rat Snake",
	"Red-Backed Rat Snake",
	"Twin-Spotted Rat Snake",
	"Yellow-Striped Rat Snake",
	"Manchurian Black Water Snake",
	"Rattlesnake",
	"Arizona Black Rattlesnake",
	"Aruba Rattlesnake",
	"Chihuahuan Ridge-Nosed Rattlesnake",
	"Coronado Island Rattlesnake",
	"Durango Rock Rattlesnake",
	"Dusky Pigmy Rattlesnake",
	"Eastern Diamondback Rattlesnake",
	"Grand Canyon Rattlesnake",
	"Great Basin Rattlesnake",
	"Hopi Rattlesnake",
	"Lance-Headed Rattlesnake",
	"Long-Tailed Rattlesnake",
	"Massasauga Rattlesnake",
	"Mexican Green Rattlesnake",
	"Mexican West Coast Rattlesnake",
	"Midget Faded Rattlesnake",
	"Mojave Rattlesnake",
	"Northern Black-Tailed Rattlesnake",
	"Oaxacan Small-Headed Rattlesnake",
	"Rattler",
	"Red Diamond Rattlesnake",
	"Southern Pacific Rattlesnake",
	"Southwestern Speckled Rattlesnake",
	"Tancitaran Dusky Rattlesnake",
	"Tiger Rattlesnake",
	"Timber Rattlesnake",
	"Tropical Rattlesnake",
	"Twin-Spotted Rattlesnake",
	"Uracoan Rattlesnake",
	"Western Diamondback Rattlesnake",
	"Ribbon Snake",
	"Rinkhals",
	"River Jack",
	"Sea Snake",
	"Annulated Sea Snake",
	"Beaked Sea Snake",
	"Dubois'S Sea Snake",
	"Hardwicke'S Sea Snake",
	"Hook Nosed Sea Snake",
	"Olive Sea Snake",
	"Pelagic Sea Snake",
	"Stoke'S Sea Snake",
	"Yellow-Banded Sea Snake",
	"Yellow-Bellied Sea Snake",
	"Yellow-Lipped Sea Snake",
	"Shield-Tailed Snake",
	"Sidewinder",
	"Colorado Desert Sidewinder",
	"Mojave Desert Sidewinder",
	"Sonoran Sidewinder",
	"Small-Eyed Snake",
	"Smooth Snake",
	"Brazilian Smooth Snake",
	"European Smooth Snake",
	"Stiletto Snake",
	"Striped Snake",
	"Japanese Striped Snake",
	"Sunbeam Snake",
	"Taipan",
	"Central Ranges Taipan",
	"Coastal Taipan",
	"Inland Taipan",
	"Paupan Taipan",
	"Tentacled Snake",
	"Tic Polonga",
	"Tiger Snake",
	"Chappell Island Tiger Snake",
	"Common Tiger Snake",
	"Down'S Tiger Snake",
	"Eastern Tiger Snake",
	"King Island Tiger Snake",
	"Krefft'S Tiger Snake",
	"Peninsula Tiger Snake",
	"Tasmanian Tiger Snake",
	"Western Tiger Snake",
	"Tigre Snake",
	"Tree Snake",
	"Blanding'S Tree Snake",
	"Blunt-Headed Tree Snake",
	"Brown Tree Snake",
	"Long-Nosed Tree Snake",
	"Many-Banded Tree Snake",
	"Northern Tree Snake",
	"Trinket Snake",
	"Black-Banded Trinket Snake",
	"Twig Snake",
	"African Twig Snake",
	"Twin Headed King Snake",
	"Titanoboa",
	"Urutu",
	"Vine Snake",
	"Asian Vine Snake, Whip Snake",
	"American Vine Snake",
	"Mexican Vine Snake",
	"Viper",
	"Asp Viper",
	"Bamboo Viper",
	"Bluntnose Viper",
	"Brazilian Mud Viper",
	"Burrowing Viper",
	"Bush Viper",
	"Great Lakes Bush Viper",
	"Hairy Bush Viper",
	"Nitsche'S Bush Viper",
	"Rough-Scaled Bush Viper",
	"Spiny Bush Viper",
	"Carpet Viper",
	"Crossed Viper",
	"Cyclades Blunt-Nosed Viper",
	"Eyelash Viper",
	"False Horned Viper",
	"Fea'S Viper",
	"Fifty Pacer",
	"Gaboon Viper",
	"Hognosed Viper",
	"Horned Desert Viper",
	"Horned Viper",
	"Jumping Viper",
	"Kaznakov'S Viper",
	"Leaf-Nosed Viper",
	"Leaf Viper",
	"Levant Viper",
	"Long-Nosed Viper",
	"Mcmahon'S Viper",
	"Mole Viper",
	"Nose-Horned Viper",
	"Rhinoceros Viper",
	"Vipera Ammodytes",
	"Palestine Viper",
	"Pallas' Viper",
	"Palm Viper",
	"Amazonian Palm Viper",
	"Black-Speckled Palm-Pitviper",
	"Eyelash Palm-Pitviper",
	"Green Palm Viper",
	"Mexican Palm-Pitviper",
	"Guatemalan Palm Viper",
	"Honduran Palm Viper",
	"Siamese Palm Viper",
	"Side-Striped Palm-Pitviper",
	"Yellow-Lined Palm Viper",
	"Pit Viper",
	"Banded Pitviper",
	"Bamboo Pitviper",
	"Barbour'S Pit Viper",
	"Black-Tailed Horned Pit Viper",
	"Bornean Pitviper",
	"Brongersma'S Pitviper",
	"Brown Spotted Pitviper",
	"Cantor'S Pitviper",
	"Elegant Pitviper",
	"Eyelash Pit Viper",
	"Fan-Si-Pan Horned Pitviper",
	"Flat-Nosed Pitviper",
	"Godman'S Pit Viper",
	"Green Tree Pit Viper",
	"Habu Pit Viper",
	"Hagen'S Pitviper",
	"Horseshoe Pitviper",
	"Jerdon'S Pitviper",
	"Kanburian Pit Viper",
	"Kaulback'S Lance-Headed Pitviper",
	"Kham Plateau Pitviper",
	"Large-Eyed Pitviper",
	"Malabar Rock Pitviper",
	"Malayan Pit Viper",
	"Mangrove Pit Viper",
	"Mangshan Pitviper",
	"Motuo Bamboo Pitviper",
	"Nicobar Bamboo Pitviper",
	"Philippine Pitviper",
	"Pointed-Scaled Pit Viper",
	"Red-Tailed Bamboo Pitviper",
	"Schultze'S Pitviper",
	"Stejneger'S Bamboo Pitviper",
	"Sri Lankan Pit Viper",
	"Temple Pit Viper",
	"Tibetan Bamboo Pitviper",
	"Tiger Pit Viper",
	"Undulated Pit Viper",
	"Wagler'S Pit Viper",
	"Wirot'S Pit Viper",
	"Portuguese Viper",
	"Rhinoceros Viper",
	"River Jack",
	"Russell'S Viper",
	"Sand Viper",
	"Saw-Scaled Viper",
	"Schlegel'S Viper",
	"Sedge Viper",
	"Sharp-Nosed Viper",
	"Snorkel Viper",
	"Temple Viper",
	"Tree Viper",
	"Chinese Tree Viper",
	"Guatemalan Tree Viper",
	"Hutton'S Tree Viper",
	"Indian Tree Viper",
	"Large-Scaled Tree Viper",
	"Malcolm'S Tree Viper",
	"Nitsche'S Tree Viper",
	"Pope'S Tree Viper",
	"Rough-Scaled Tree Viper",
	"Rungwe Tree Viper",
	"Sumatran Tree Viper",
	"White-Lipped Tree Viper",
	"Ursini'S Viper",
	"Western Hog-Nosed Viper",
	"Wart Snake",
	"Water Moccasin",
	"Water Snake",
	"Bocourt'S Water Snake",
	"Northern Water Snake",
	"Whip Snake",
	"Long-Nosed Whip Snake",
	"Wolf Snake",
	"African Wolf Snake",
	"Barred Wolf Snake",
	"Worm Snake",
	"Common Worm Snake",
	"Longnosed Worm Snake",
	"Wutu",
	"Yarara",
	"Zebra Snake",
}
