package english

type Dog = string

var dogs = []Dog{
	"Affenpinscher",
	"Afghan Hound",
	"Airedale Terrier",
	"Akita Inu",
	"Alaskan Malamute",
	"Alpine Dachsbracke",
	"American Akita",
	"American Bulldog",
	"American Cocker Spaniel",
	"American Foxhound",
	"American Staffordshire Terrier",
	"American Water Spaniel",
	"Anatolian Shepherd",
	"Appenzell Cattle Dog",
	"Ariege Pointing Dog",
	"Ariegeois",
	"Artois Hound",
	"Atlas Mountain Dog (Aidi)",
	"Australian Cattle Dog",
	"Australian Kelpie",
	"Australian Shepherd",
	"Australian Silky Terrier",
	"Australian Terrier",
	"Austrian Black",
	"Austrian Pinscher",
	"Auvergne Pointer",
	"Azawakh",
	"Basenji",
	"Basset Fauve de Bretagne",
	"Basset Hound",
	"Bavarian Mountain Scent Hound",
	"Beagle",
	"Beagle Harrier",
	"Bearded Collie",
	"Bedlington Terrier",
	"Belgian Shepherd",
	"Bergamasco Shepherd Dog",
	"Bernese Mountain Dog",
	"Bichon Frise",
	"Billy",
	"Black and Tan Coonhound",
	"Bloodhound",
	"Blue Gascony",
	"Blue Picardy Spaniel",
	"Boerboel",
	"Bohemian Wire-haired Pointing Griffon",
	"Bolognese",
	"Border Collie",
	"Border Terrier",
	"Borzoï",
	"Bosnian Broken-haired Hound - Called Barak",
	"Boston Terrier",
	"Bourbonnais Pointing Dog",
	"Bouvier de",
	"Bouvier des Flandres",
	"Boxer",
	"Bracco Italiano (Italian Pointing dog)",
	"Brazilian Terrier",
	"Briard",
	"Briquet Grif",
	"Brittany",
	"Broholmer",
	"Bull Terrier",
	"Bulldog",
	"Bullmastiff",
	"Burgos Pointing Dog",
	"Cairn Terrier",
	"Canaan Dog",
	"Canarian Warren Hound",
	"Cane Corso",
	"Castro Laboreiro Dog",
	"Catalan Sheepdog",
	"Caucasian Shepherd Dog",
	"Cavalier King Charles Spaniel",
	"Central Asia Shepherd Dog",
	"Cesky Terrier",
	"Chesapeake Bay Retriever",
	"Chihuahua",
	"Chinese Crested Dog",
	"Chow Chow",
	"Cirneco Dell'Etna",
	"Clumber Spaniel",
	"Coarse-haired ",
	"Cocker Spaniel",
	"Collie Smooth",
	"Coton de Tulear",
	"Croatian Shepherd Dog",
	"Curly-Coated Retriever",
	"Curs",
	"Czechoslovakian Wolfdog",
	"Dachshund",
	"Dalmatian",
	"Dandie Dinmont Terrier",
	"Deerhound",
	"Deutsch ",
	"Deutsch Stichelhaar",
	"Dobermann",
	"Dogo Argentino",
	"Dogue de Bordeaux",
	"Drentsche Partridge Dog",
	"Drever",
	"Dutch Schapendoes",
	"Dutch Shepherd",
	"Dutch Smoushond",
	"East Siberian Laika",
	"English ",
	"English Pointer",
	"English Setter",
	"English Springer Spaniel",
	"English Toy Terrier (Black & Tan)",
	"Entlebuch Cattle Dog",
	"Estrela Mountain Dog",
	"Eurasier",
	"Fawn Britt",
	"Field Spaniel",
	"Fila Brasileiro",
	"Finnish Hound",
	"Finnish Lapponian Dog",
	"Finnish Spitz",
	"Flat-Coated Retriever",
	"Fox Terrier",
	"French Bulldog",
	"French Poi",
	"French Spaniel",
	"French Tricolour Hound",
	"French Water Dog",
	"French White & Black Hound",
	"French White &",
	"Frisian Water Dog",
	"Gascon Saintongeois",
	"German Hound",
	"German Hunting Terrier",
	"German Shepherd",
	"German Shorthaired Pointer",
	"German Spaniel",
	"German Wirehair",
	"Golden Retriever",
	"Gordon Setter",
	"Grand Basset Griffon Vendeen",
	"Grand Griffon Vendeen",
	"Great Anglo-French Tricolour Hound",
	"Great Anglo-French White & Black Hound",
	"Great Anglo-French White & Orange Hound",
	"Great Dane",
	"Great Swiss Mountain Dog",
	"Greek Harehound",
	"Greenland Dog",
	"Greyhound",
	"Griffon Belge",
	"Griffon Bruxellois",
	"Griffon Nivernais",
	"Halden Hound",
	"Hamiltonstövare",
	"Hanoverian ",
	"Harrier",
	"Havanese",
	"Hokkaido",
	"Hovawart",
	"Hungarian Greyhound",
	"Hungarian Hound - Transylvanian Scent Hound",
	"Hungarian Vizsla",
	"Husky",
	"Hygen Hound",
	"Ibizan Podenco",
	"Icelandic Sheepdog",
	"Irish Glen of Imaal Terrier",
	"Irish Red and White Setter",
	"Irish Red Setter",
	"Irish Soft-coated Wheaten Terrier",
	"Irish Terrier",
	"Irish Water Spaniel",
	"Irish Wolfhound",
	"Istrian Short",
	"Istrian Wire-haired Hound",
	"Italian Segugio",
	"Italian Sighthound",
	"Italian Spinone",
	"Italian Volpino",
	"Jack Russell Terrier",
	"Jämthund",
	"Japanese Chin",
	"Japanese Shiba Inu",
	"Japanese Spitz",
	"Japanese",
	"Kai Ken",
	"Karelian Bear Dog",
	"Karst Shepherd Dog",
	"Kerry Blue Terrier",
	"King Charl",
	"Kishu",
	"Kleiner Münsterländer",
	"Komondor",
	"Korea Jindo Dog",
	"Kromfohrländer",
	"Kuvasz",
	"Labrador",
	"Lagotto Romagnolo (Romagna Water Dog)",
	"Lakeland",
	"Landseer",
	"Lapponian Herder",
	"Large Munsterlander",
	"Leonberger",
	"Lhasa Apso",
	"Little Lion Dog",
	"Majorca Mastiff",
	"Majorca Shepherd Dog",
	"Maltese",
	"Manchester Terrier",
	"Maremma and the Abruzzes Sheepdog",
	"Mastiff",
	"Medium-sized Anglo-French Hound",
	"Montenegrin Mountain Hound",
	"Mudi",
	"Neapolitan Mastiff",
	"Nederlandse Kooikerhondje",
	"Newfoundland",
	"Norfolk Terrier and Norwich Terrier",
	"Norman Artesien Basset",
	"Norrbottenspitz",
	"Norwegian Buhund",
	"Norwegian Elkhound Grey",
	"Norwegian Hound",
	"Norwegian Lundehund",
	"Nova Scotia Duck Tolling Retriever",
	"Old Danish P",
	"Old English Sheepdog",
	"Otterhound",
	"Papillon (Continental Toy Spaniel)",
	"Parson Russell Terrier",
	"Pekingese",
	"Peruvian Hairless Dog",
	"Petit Basset Griffon Vendeen",
	"Petit Brabançon",
	"Pharaoh Hound",
	"Picardy Sheepdog",
	"Picardy Spaniel",
	"Pinscher",
	"Poitevin",
	"Polish Greyhound",
	"Polish Hound",
	"Polish Hunting Dog",
	"Polish Lowland Sheepdog",
	"Pomeranian or miniature Spitz",
	"Pont-Audemer Spaniel",
	"Poodle",
	"Porcelaine",
	"Portuguese Pointing Dog",
	"Portuguese Sheepdog",
	"Portuguese Warren Hound",
	"Portuguese Water Dog",
	"Posavat",
	"Presa Canario (Canary Mastiff)",
	"Pudelpointer",
	"Pug",
	"Puli",
	"Pyrenean Mastiff",
	"Pyrenean M",
	"Pyrenean Sheepdog",
	"Rafeiro of Alentejo",
	"Rhodesian Ridgeback",
	"Rottweiler",
	"Rough Collie",
	"Russian Black Terrier",
	"Russian Toy",
	"Russian-European Laika",
	"Saarloos Wolfhound",
	"Saint Germain Pointer",
	"Saint Miguel Cattle Dog",
	"Saluki",
	"Samoyed",
	"Schillerstövare",
	"Schipperke",
	"Schnauzer",
	"Scottish Terrier",
	"Sealyham Terrier",
	"Serbian Hound",
	"Serbian Tricolour Hound",
	"Shar Pei",
	"Shetland Sheepdog",
	"Shih Tzu",
	"Shikoku",
	"Skye Terrier",
	"Sloughi",
	"Slovakian Chuvach",
	"Slovakian Hound",
	"Smålandsstövare",
	"Small Gascon Saintongeois",
	"Small Swiss Hound",
	"South Russian Shepherd Dog",
	"Spanish Greyhound",
	"Spanish Hound",
	"Spanish Mastiff",
	"Spanish Water Dog",
	"St. Bernard",
	"Stabijhoun",
	"Staffordshire Bull Terrier",
	"Sussex Spaniel",
	"Swedish Lapphund",
	"Swedish Vallhund",
	"Swiss Hound",
	"Taiwan Dog",
	"Tatra Shepherd Dog",
	"Thai Ridgeback Dog",
	"Tibetan Mastiff",
	"Tibetan Spaniel",
	"Tibetan Terrier",
	"Tosa",
	"Tyrolean Hound",
	"Weimaraner",
	"Welsh Corgi",
	"Welsh Springer Spaniel",
	"Welsh Terrier",
	"West Highland White Terrier",
	"West Siberian Laika",
	"Westphalian Dachsbracke",
	"Whippet",
	"White Swiss Shepherd Dog",
	"Wire-haired Pointing Griffon Korthals",
	"Wirehaired Slovakian Pointer",
	"Xoloitzcuintle",
	"Yorkshire Terrier",
	"Yugoslavian Shepherd Dog",
}
