package main

type Insects = []string

var insects = Insects{
	"Admiral Butterfly",
	"Ambush Bug",
	"Aphid",
	"Armyworm",
	"Assassin Bug",
	"Atlas Moth",
	"Backswimmer",
	"Bedbug",
	"Bee",
	"Blue Morpho Butterfly",
	"Bluet",
	"Borer",
	"Bumblebee",
	"Carpenter Ant",
	"Caterpillar",
	"Chrysalis",
	"Cicada",
	"Cockroach",
	"Crane Fly",
	"Cricket",
	"Cutworm",
	"Damselfly",
	"Darkling Beetle",
	"Dragonfly",
	"Dung Beetle",
	"Earwig",
	"Fire Ant",
	"Firefly",
	"Flea",
	"Fruit Fly",
	"Gnat",
	"Grasshopper",
	"Green Darner Dragonfly",
	"Ground Beetle",
	"Grub",
	"Gypsy Moth",
	"Harlequin Bug",
	"Honeybee",
	"Hornet",
	"Horse Fly",
	"House Fly",
	"Insect",
	"Japanese Beetle",
	"Jumping Bean",
	"June Bug",
	"Katydid",
	"Kissing Bug",
	"Lacewing",
	"Ladybug",
	"Larva",
	"Leafcutter Ant",
	"Leafhopper",
	"Lice",
	"Lightning Bug",
	"Locust",
	"Longhorn Beetle",
	"Louse",
	"Luna Moth",
	"Maggot",
	"Mantid",
	"Mantis",
	"Mayfly",
	"Meadowhawk",
	"Mealworm",
	"Midge",
	"Milkweed Bug",
	"Monarch",
	"Morpho",
	"Mosquito",
	"Moth",
	"Nymph",
	"Owl Butterfly",
	"Paper Wasp",
	"Planthopper",
	"Pond Skater",
	"Praying Mantid",
	"Praying Mantis",
	"Robber Fly",
	"Scarab",
	"Silkworm",
	"Silverfish",
	"Skipper",
	"Spittlebug",
	"Springtail",
	"Stag Beetle",
	"Stink Bug",
	"Stonefly",
	"Termite",
	"Thrip",
	"Tiger Beetle",
	"Tiger Moth",
	"Tsetse Fly",
	"Ulysses Butterfly",
	"Viceroy Butterfly",
	"Walking Stick",
	"Wasp",
	"Water Boatman",
	"Water Bug",
	"Water Strider",
	"Weevil",
	"Wood Nymph Butterfly",
	"Wood-Borer",
	"Woolly Bear Caterpillar",
	"Yellowjacket",
	"Zebra Longwing Butterfly",
	"Zebra Swallowtail Butterfly",
}
