package main

type Cows = []string

var cows = Cows{
	"Aberdeen Angus",
	"Africander",
	"Aubrac",
	"Ayrshire",
	"Barzona",
	"Bazadaise",
	"Beef Shorthorn",
	"Beefalo",
	"Beefmaster",
	"Belgian Blue",
	"Belmont Red",
	"Belted Galloway",
	"Blonde d'Aquitaine",
	"Bonsmara",
	"Boran",
	"Braford",
	"Brahman",
	"Brahmousin",
	"Brangus",
	"British White",
	"Brown Swiss",
	"Buelingo",
	"Busa",
	"Canadienne",
	"Canchim",
	"Caracu",
	"Charolais",
	"Chianina",
	"Composite",
	"Corriente",
	"Dairy Shorthorn",
	"Devon",
	"Dexter",
	"Drakensberger",
	"Droughtmaster",
	"Dutch Belted",
	"English Longhorn",
	"Estonian Red",
	"Fleckvieh",
	"Friesian",
	"Galloway",
	"Gelbvieh",
	"Girolando",
	"Gloucester",
	"Guernsey",
	"Hays Converter",
	"Hereford",
	"Highland",
	"Holstein",
	"Hybridmaster",
	"Illawarra",
	"Irish Moiled",
	"Jersey",
	"Kerry",
	"Limousin",
	"Lincoln Red",
	"Lineback",
	"Lowline",
	"Luing",
	"Maine-Anjou (Rouge des Prés)",
	"Marchigiana",
	"Meuse Rhine Issel",
	"Milking Devon",
	"Miniature Hereford",
	"Mirandesa",
	"Mongolian",
	"Montbéliarde",
	"Murray Grey",
	"Nelore",
	"Nguni",
	"Normande",
	"Norwegian Red",
	"Parthenais",
	"Piemontese",
	"Pinzgauer",
	"Randall",
	"Red Angus",
	"Red Poll",
	"Retinta",
	"Romagnola",
	"Sahiwal",
	"Salers",
	"Sanganer",
	"Santa Cruz",
	"Santa Gertrudis",
	"Senepol",
	"Shetland",
	"Simbrah",
	"Simmental",
	"South Devon",
	"Speckle Park",
	"Square Meaters",
	"Sussex",
	"Tarentaise",
	"Texas Longhorn",
	"Tuli",
	"Wagyu",
	"Watusi",
	"Welsh Black",
	"Whitebred Shorthorn",
	"Zebu",
}
