package main

type Rodents = []string

var rodents = Rodents{
	"Anomalure",
	"Spring Hare",
	"Beaver",
	"Giant Beaver ",
	"Kangaroo Mouse",
	"Kangaroo Rat",
	"Pocket Mouse",
	"Pocket Gopher",
	"AgoutiFamily ",
	"Acouchy",
	"Agouti",
	"American Spiny Rat",
	"Blesmol",
	"Cane Rat",
	"Capybara",
	"Guinea Pig",
	"Mara",
	"Chinchilla",
	"Viscacha",
	"Chinchilla Rat",
	"Dassie Rat",
	"Degu",
	"Gundi",
	"Hutia Family ",
	"Hutia",
	"New World Porcupine",
	"Nutria",
	"Paca",
	"Pacarana",
	"Tuco-Tuco",
	"American Harvest Mouse",
	"Cotton Rat",
	"Deer Mouse",
	"Grasshopper Mouse",
	"Hamster",
	"Golden Hamster",
	"Lemming",
	"Maned Rat",
	"Muskrat",
	"Rice Rat",
	"Vole",
	"Meadow Vole",
	"Woodland Vole",
	"Water Rat",
	"Woodrat",
	"Birch Mouse",
	"Jerboa",
	"Jumping Mouse",
	"African Spiny Mouse",
	"Bandicoot Rat",
	"Cloud Rat",
	"Gerbil",
	"Sand Rat",
	"Mouse",
	"House Mouse",
	"Shrew Rat",
	"Water Rat",
	"Wood Mouse",
	"African Pouched Rat",
	"Asian Tree Mouse",
	"Bamboo Rat",
	"Blind Mole Rat",
	"Zokor",
	"Dormouse",
	"Desert Dormouse",
	"Mountain Beaver",
	"Chipmunk",
	"Flying Squirrel",
	"Ground Squirrel",
	"Suslik",
	"Marmot",
	"Groundhog",
	"Prairie Dog",
	"Tree Squirrel",
}
