package english

type Bird = string

var birds = []Bird{
	"Adelie Penguin",
	"African Fish Eagle",
	"African Grey Parrot",
	"African Jacana",
	"African Penguin",
	"Albatross",
	"Amazon Parrot",
	"Amazonian Royal Flycatcher",
	"American Robin",
	"Anhinga",
	"Anna’S Hummingbird",
	"Australian Firehawk",
	"Avocet",
	"Ayam Cemani",
	"Bald Eagle",
	"Barn Owl",
	"Barn Swallow",
	"Barred Owl",
	"Baya",
	"Bearded Vulture",
	"Bee-Eater",
	"Belgian Canary",
	"Belted Kingfisher",
	"Bird",
	"Bird Of Paradise",
	"Black And White Warbler",
	"Black-Bellied Whistling Duck",
	"Black-Capped Chickadee",
	"Blackburnian Warbler",
	"Blackpoll Warbler",
	"Blue Gray Gnatcatcher",
	"Blue Grosbeak",
	"Blue Jay",
	"Blue Tit",
	"Bobolink",
	"Booby",
	"Bronze-Winged Jacana",
	"Brown Headed Cowbird",
	"Budgerigar",
	"Burrowing Owl",
	"Cactus Wren",
	"Canada Warbler",
	"Cardinal",
	"Carolina Parakeet",
	"Cassowary",
	"Cedar Waxwing",
	"Chestnut-Sided Warbler",
	"Chickadee",
	"Chicken",
	"Chinese Geese",
	"Chinstrap Penguin",
	"Chipping Sparrow",
	"Cinereous Vulture",
	"Clark’S Grebe",
	"Cockatiel",
	"Cockatoo",
	"Comb-Crested Jacana",
	"Common Buzzard",
	"Common Grackle",
	"Common Green Magpie",
	"Common Loon",
	"Common Raven",
	"Common Yellowthroat",
	"Conure",
	"Cooper’S Hawk",
	"Cormorant",
	"Costa’S Hummingbird",
	"Crane",
	"Crested Penguin",
	"Crow",
	"Cuckoo",
	"Dark-Eyed Junco",
	"Dark-Eyed Junco",
	"Dodo",
	"Downy Woodpecker",
	"Dromornis Stirtoni",
	"Duck",
	"Dunnock",
	"Eagle",
	"Eared Grebe",
	"Eastern Bluebird",
	"Eastern Kingbird",
	"Eastern Meadowlark",
	"Eastern Phoebe",
	"Eastern Turkey ",
	"Eclectus Parrot",
	"Egyptian Goose",
	"Egyptian Vulture",
	"Eider",
	"Elegant Tern",
	"Elephant Bird",
	"Elf Owl",
	"Emerald Toucanet",
	"Emperor Penguin",
	"Emu",
	"Eurasian Bullfinch",
	"Eurasian Collared Dove",
	"Eurasian Eagle-Owl",
	"Eurasian Jay",
	"Eurasian Nuthatch",
	"Eurasian Sparrowhawk",
	"European Bee-Eater",
	"European Goldfinch",
	"European Robin",
	"European Starling",
	"Evening Grosbeak",
	"Fairy-Wren",
	"Falcon",
	"Ferruginous Hawk",
	"Flamingo",
	"Frigatebird",
	"Galapagos Penguin",
	"Gentoo Penguin",
	"Goldcrest",
	"Golden Masked Owl",
	"Golden Oriole",
	"Golden-Crowned Kinglet",
	"Goose",
	"Goshawk",
	"Gouldian Finch",
	"Gray Catbird",
	"Great Blue Heron",
	"Great Crested Flycatcher",
	"Great Egret",
	"Great Kiskadee",
	"Great Potoo Bird",
	"Grebe",
	"Green Bee-Eater",
	"Green Heron",
	"Grey Heron",
	"Griffon Vulture",
	"Grouse",
	"Guinea Fowl",
	"Hairy Woodpecker",
	"Harpy Eagle",
	"Harris Hawk",
	"Hawaiian Crow",
	"Hawaiian Goose ",
	"Hawk",
	"Hepatic Tanager ",
	"Heron",
	"Herring Gull",
	"Honey Buzzard",
	"Hooded Oriole",
	"Hoopoe",
	"Hornbill",
	"House Finch",
	"House Sparrow ",
	"House Wren",
	"Humboldt Penguin",
	"Hummingbird",
	"Hyacinth Macaw",
	"Ibis",
	"Ivory-Billed Woodpecker",
	"Jabiru",
	"Jacana",
	"Jackdaw",
	"Junglefowl",
	"Kagu",
	"Kakapo",
	"Kaua’I ‘Ō‘Ō",
	"Keel-Billed Toucan",
	"Kentucky Warbler",
	"Kestrel",
	"Killdeer",
	"King Penguin",
	"King Quail",
	"King Vulture",
	"Kingfisher",
	"Kiwi",
	"Kookaburra",
	"Kori Bustard",
	"Lappet-Faced Vulture",
	"Lesser Jacana",
	"Linnet",
	"Little Penguin",
	"Long-Eared Owl",
	"Long-Tailed Tit",
	"Lorikeet",
	"Lyrebird",
	"Macaroni Penguin",
	"Macaw",
	"Macgillivray’S Warbler",
	"Madagascar Jacana",
	"Magellanic Penguin",
	"Magnolia Warbler",
	"Magpie",
	"Mallard",
	"Marabou Stork",
	"Mexican Eagle ",
	"Mississippi Kite",
	"Mountain Bluebird",
	"Mourning Dove",
	"Mourning Warbler",
	"Muscovy Duck",
	"Myna Bird",
	"Nicobar Pigeon",
	"Night Heron",
	"Nightingale",
	"Nightjar",
	"Northern Cardinal",
	"Northern Flicker",
	"Northern Jacana",
	"Northern Potoo",
	"Northern Screamer",
	"Nuthatch",
	"Orange-Crowned Warbler",
	"Orchard Oriole",
	"Oriental Dwarf Kingfisher",
	"Ortolan Bunting",
	"Osprey",
	"Ostrich",
	"Ovenbird",
	"Owl",
	"Oxpecker",
	"Parakeet",
	"Parrot",
	"Parrotlet",
	"Partridge",
	"Peacock",
	"Pelican",
	"Penguin",
	"Peregrine Falcon",
	"Pesquet’S Parrot ",
	"Pheasant-Tailed Jacana",
	"Phoenix Chicken",
	"Pied-Billed Grebe",
	"Pigeon",
	"Pileated Woodpecker",
	"Pine Siskin",
	"Pink-Necked Green Pigeon",
	"Potoo",
	"Prairie Chicken",
	"Puffin",
	"Purple Finch",
	"Purple Gallinule",
	"Quail",
	"Quetzal",
	"Red Finch",
	"Red Kite",
	"Red-Bellied Woodpecker",
	"Red-Billed Quelea Bird",
	"Red-Shouldered Hawk",
	"Red-Winged Blackbird",
	"Redstart",
	"Rhea",
	"Ring-Billed Gull",
	"Ringed Kingfisher",
	"Robin",
	"Rockhopper Penguin",
	"Rooster",
	"Rose-Breasted Grosbeak",
	"Roseate Spoonbill",
	"Royal Penguin",
	"Ruby-Crowned Kinglet",
	"Ruby-Throated Hummingbird",
	"Ruddy Turnstone",
	"Rufous Hummingbird",
	"Sandhill Crane",
	"Sandpiper",
	"Sarus Crane",
	"Savannah Sparrow",
	"Scale-Crested Pygmy Tyrant",
	"Scarlet Macaw",
	"Sea Eagle",
	"Seagull",
	"Sedge Warbler",
	"Senegal Parrot",
	"Sharp-Shinned Hawk",
	"Shoebill Stork",
	"Short-Eared Owl",
	"Silkie Chicken",
	"Skua",
	"Snow Bunting",
	"Snowy Owl",
	"Song Sparrow",
	"Song Thrush",
	"Sparrow",
	"Sparrowhawk",
	"Spixs Macaw",
	"Stork",
	"Summer Tanager",
	"Swainson’S Hawk",
	"Swallow",
	"Swan",
	"Tawny Frogmouth",
	"Tawny Owl",
	"Thrush",
	"Toucan",
	"Towhee",
	"Tree Swallow",
	"Treecreeper",
	"Tropicbird",
	"Tufted Coquette",
	"Tufted Titmouse",
	"Turaco",
	"Turkey",
	"Turkey Vulture",
	"Uguisu",
	"Umbrellabird",
	"Ural Owl",
	"Vermilion Flycatcher",
	"Vulture",
	"Wandering Albatross",
	"Warbler",
	"Wattled Jacana",
	"Weaver Bird",
	"Western Tanager",
	"Whimbrel",
	"Whinchat",
	"White-Crowned Sparrow",
	"White-Tailed Eagle",
	"Whooping Crane",
	"Willow Warbler",
	"Woodpecker",
	"Wryneck",
	"Xeme ",
	"Yellow Bellied Sapsucker",
	"Yellow-Eyed Penguin",
	"Yellowhammer",
	"Yokohama Chicken",
}
