package english

type Cat = string

var cats = []Cat{
	"Abyssinian Cat",
	"American Bobtail",
	"American Curl",
	"American Shorthair",
	"American Wirehair",
	"Balinese cat",
	"Bengal",
	"Birman",
	"Bombay",
	"British Longhair",
	"British Shorthair",
	"Burmese",
	"Burmilla",
	"California Spangled",
	"Californ",
	"Ceylon",
	"Chartreux",
	"Chausie",
	"Chinchilla Persian",
	"Cornish Rex",
	"Cymric",
	"Devon Rex",
	"Domestic shorthair",
	"Donskoy",
	"Egyptian Mau",
	"European Shorthair",
	"Exotic shorthair",
	"German Rex",
	"Havana Brown",
	"Highland Fold",
	"Himalayan",
	"Japanese Bobtail",
	"Javanese",
	"Khao Manee",
	"Korat",
	"LaPerm",
	"Maine Coon",
	"Manx",
	"Munchkin",
	"Nebelung",
	"Norwegian Forest cat",
	"Ocicat",
	"Oriental",
	"Persian",
	"Peterbald",
	"Pixie-bob",
	"Ragamuffin",
	"Ragdoll",
	"Russian Blue",
	"Safari",
	"Savannah",
	"Scottish Fold",
	"Selkirk Rex",
	"Siamese Cat",
	"Siberian cat",
	"Singapura",
	"Snowshoe",
	"Sokoke",
	"Somali",
	"Sphynx",
	"Thaï",
	"Tiffany",
	"Tonkinese",
	"Toyger",
	"Turkish Angora",
	"Turkish Van",
	"York Chocolate",
}
