package english

type Cetacean = string

var cetaceans = []Cetacean{
	"African Helmeted Turtle",
	"Alabama Red-Bellied Cooter",
	"Alligator Snapping Turtle",
	"Giant River Turtle",
	"Asian Giant Softshell Turtle",
	"Big-Headed Turtle",
	"Common Box Turtle",
	"Common Musk Turtle",
	"Common Snapping Turtle",
	"Desert Tortoise",
	"Diamondback Terrapin",
	"East African Black Mud Turtle",
	"Eastern Long-Necked Turtle",
	"False Map Turtle",
	"Florida Softshell Turtle",
	"Four-Eyed Turtle",
	"Green Sea Turtle",
	"Hickatee",
	"Leatherback Sea Turtle",
	"Malaysian Giant Turtle",
	"Ornate Box Turtle",
	"Painted Turtle",
	"Pig-Nosed Turtle",
	"Pond Slider",
	"Roti Island Snake-Necked Turtle",
	"Spiny Softshell Turtle",
	"Spotted Turtle",
	"Striped Mud Turtle",
	"Western Swamp Turtle",
}
